Create TABLE income (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR2(100),
    amount NUMBER(10, 2),
    date_received DATE
);

CREATE TABLE expenses (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR2(100),
    amount NUMBER(10, 2),
    date_spent DATE,
    description VARCHAR2
);

CREATE TABLE categories (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100),
    type VARCHAR2(10) -- 'Income' or 'Expense'
);